Show proposal time-stamp instead of block counts
particl/particl-desktop pull request #1248
Opened 2018-11-12 13:57 UTC by cis-shubham-t

Task: https://particl.atlassian.net/projects/PD/issues/PD-459

2018-11-12 14:22 UTC, cis-shubham-t commented
testing needed!!

2018-11-12 15:09 UTC, zaSmilingIdiot requested changes

2018-11-12 15:09 UTC, zaSmilingIdiot commented on src/app/wallet/proposals/models/proposal.model.ts
> +  getTimeStamp(type: string): String {
The type parameter here is unnecessary - the condition below can be based on whether `this.expiredAt > Date.now()`

2018-11-12 15:09 UTC, zaSmilingIdiot commented on src/app/wallet/proposals/proposal-details/proposal-details.component.html
> +      <div class="text">{{proposal?.getTimeStamp('left')}} time left</div>
No need for the parameter

2018-11-12 15:09 UTC, zaSmilingIdiot commented on src/app/wallet/proposals/proposal-details/proposal-details.component.html
> +      <div class="text">{{proposal?.getTimeStamp('left')}} time left until voting starts</div>
No need for the parameter

2018-11-12 15:09 UTC, zaSmilingIdiot commented on src/app/wallet/proposals/proposal-details/proposal-details.component.html
> +      <div class="text">voting finished {{proposal?.getTimeStamp('ago')}} ago</div>
No need for the parameter

2018-11-14 10:55 UTC, zaSmilingIdiot approved these changes

2018-11-14 10:56 UTC, merged