Listing item information update (Edit un-published listing)
particl/particl-desktop pull request #1262
Opened 2018-11-15 08:37 UTC by cis-shubham-t

2018-12-03 11:11 UTC, zaSmilingIdiot requested changes
Can the payment.service.ts and shipping.service.ts functions not be included in the template service rather than creating what is essentially single function service values? This keeps the template information together, and saves importing additional services unnecessarily.

Yes, I realize that the escrow, information, etc services all do this, but its unnecessary unless the service provides functionality that is useful (and is used) on its own. In this case, it really is not used separately from the remainder oft he template functionality, and so we can keep the functionality together.

2018-12-03 11:11 UTC, zaSmilingIdiot commented on src/app/market/sell/add-item/add-item.component.html
> +            <mat-select placeholder="Listing expiration" [disabled]="isExistingTemplate()" [(ngModel)]="expiration" (change)="loadTransactionFee()">
When editing a saved template, the 'Listing & Expiration fees' select is not editable because of this condition. However, if the user wishes to now Save and Publish the listing, they are not able to edit this field. 

A better option may be to not disable editing of this field. Instead, perhaps an option would be to display a large notification below this input if the template has an 'unpublished status', informing the user that they may need to edit this field as it is not saved as part of the template.

2018-12-03 15:25 UTC, cis-shubham-t commented
Hey @zaSmilingIdiot 
As per our discussion, I added the 'select expiry time' option in the expiry dropdown by the same we can assure that user selected the expiry time as we are not providing the expiry time edit feature for now while the edit listing.

2018-12-06 09:02 UTC, cis-shubham-t commented
hey @AllienWorks 
I've moved the listing expiry drop-down in the separate modal now. There is some UI fixes and changes required could you please have looked over it and make the proper and better.

2018-12-06 13:52 UTC, AllienWorks commented
There is a bug – Listings that are saved for later (not published immediately) and then Published later from Sell > Listings, don't trigger the expiration modal & Listings get published right away.

Plus I have some weird behaviour with my "Silver Pineapple" Listing:
- in Sell > Listings, I can see it as "Unpublished" (even if it's already published and visible on Market)
- it behaves like someone else's Listing (I can put it in my cart, even if I own it)
- tried to buy it and yes – I can buy/sell it to myself (Order shows up both in my Sell and Buy), but when Rejecting/Accepting the bid, I'm getting `Not your ListingItem` error

This Listing was published like I described in first paragraph (saved for later, published afterwards). Tried another time (with "Private $PARTyville Island"), but that one is behaving correctly for some reason.

---

@cis-shubham-t you had a typo in the component, so I renamed it, FYI.

2018-12-06 14:58 UTC, AllienWorks commented
Styling done, passing this back to you @cis-shubham-t

2018-12-12 13:58 UTC, zaSmilingIdiot approved these changes
Seems to work as expected now :)

2018-12-12 14:02 UTC, merged