added listing details to listings on buy page
particl/particl-desktop pull request #1320
Opened 2018-12-13 14:00 UTC by EagleEye25

2018-12-18 07:33 UTC, zaSmilingIdiot commented
@EagleEye25 please resolve the merge conflicts :)

2018-12-18 08:11 UTC, zaSmilingIdiot requested changes

2018-12-18 08:11 UTC, zaSmilingIdiot commented on src/app/market/buy/checkout-process/checkout-process.component.ts
> +    if (new Date().getTime() < listing.listing.expiredAt) {
Rather than duplicating the expiry check here, use the `this.checkExpired()` function (which does this check already)

2018-12-18 08:11 UTC, zaSmilingIdiot commented on src/app/market/buy/checkout-process/checkout-process.component.html
> +                <img src="{{listing.imageCollection?.featuredImage?.thumbnail}}" (click)="openListing(listing)"
If the listing has been disabled due to an error message, then there is still the indication to the user to "click here for more information". Should such "help" indicators not be removed when the action indicated has been disabled/removed?

2018-12-18 08:11 UTC, zaSmilingIdiot commented on src/app/market/buy/checkout-process/checkout-process.component.html
> +                  matTooltip="Click for more info" matTooltipPosition="above">
If the listing has been disabled due to an error message, then there is still the indication to the user to "click here for more information". Should such "help" indicators not be removed when the action indicated has been disabled/removed?

2018-12-18 10:49 UTC, EagleEye25 commented
@AllienWorks i have found an issue with the scss, this is only present on high resolution monitors.
on high res screens the lines that are showed to indicate that the item is not accessible do not show, but on normal 1080p monitors it does:
screen shot from 4k monitor 
![ss 2018-12-18 at 12 44 01](https://user-images.githubusercontent.com/28861857/50149171-1d011800-02c3-11e9-8549-18aba7fc72a2.png)
if it would be possible to find a work around this, that would be great.
i would also like to ask if you would be able to change the cursor to the normal cursor when hovering over the expired item. so it doesnt look like you can click on it when its expired.
please and thank you :D

2018-12-18 10:54 UTC, EagleEye25 commented
just realized that on your screen, you will still see the lines from the screenshot, this is how it looks from my end (picture taken from my phone):
![20181218_125214](https://user-images.githubusercontent.com/28861857/50149488-014a4180-02c4-11e9-9cbe-d1e2bdcaca8b.jpg)

2018-12-18 14:36 UTC, AllienWorks commented
Will look into it right away :)

2018-12-18 16:43 UTC, AllienWorks commented
@EagleEye25 I've fixed the layout issue with images (probably a bad merge) & styled the Expired ones a bit better. However as I don't have any expired listings in my cart, I can't really check.

Also I can't reproduce the issue with stripes you're describing. I've tried smaller and larger viewport widths, seem to work all right.

2018-12-18 17:02 UTC, zaSmilingIdiot commented
I think the problem with the stripes is 4k resolution related (rather than
dimensional changes). Specifically, I think that the stripes are thin
enough that the pixels used to respresent them on a 4k resolution are
"lost". Zooming will probably show the lines correctly, but a 1 pixel wide
line, for example, is so thin on a 4k resolution that it is not visible.
Hope that makes some sense (my terminology may be somewhat off) :)

On Tue, 18 Dec 2018, 18:43 Martin Allien <notifications@github.com wrote:

> @EagleEye25 <https://github.com/EagleEye25> I've fixed the layout issue
> with images (probably a bad merge) & styled the Expired ones a bit better.
> However as I don't have any expired listings in my cart, I can't really
> check.
>
> Also I can't reproduce the issue with stripes you're describing. I've
> tried smaller and larger viewport widths, seem to work all right.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/particl/particl-desktop/pull/1320#issuecomment-448286967>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AdIsqyH-HVMSijxahtlLniFj08dwvHJ6ks5u6Rs8gaJpZM4ZRr5k>
> .
>

2018-12-18 17:03 UTC, EagleEye25 commented
I'll check it out tomorrow when I get to the office, to see if the issue still persists

2018-12-19 10:33 UTC, vikas-cis commented
@zaSmilingIdiot accept that comment I think the pr looks good to me :)

2018-12-19 11:05 UTC, AllienWorks commented
> @zaSmilingIdiot: I think that the stripes are thin enough that the pixels used to respresent them on a 4k resolution are "lost". Zooming will probably show the lines correctly, but a 1 pixel wide line, for example, is so thin on a 4k resolution that it is not visible.

I don't think this is possible. 1px is always 1px, no matter how large your resolution is. Sure, it will be smaller, but I doubt 4k monitors lose details like that. Moreover, the stripe is ~2px wide.

I suppose you're still seeing the borders around these comments on Github, right? Those are 1px wide..

2018-12-19 11:07 UTC, AllienWorks commented
@EagleEye25 Another thing that comes to my mind is your monitor brightness/contrast. You Particl Desktop looks kinda "overburnt".. do you maybe have some non-default profile set up? You know, those "Gaming/Movie" presets etc.

2018-12-19 11:20 UTC, zaSmilingIdiot commented
The lines are definitely there, and the 1 pixel width being "lost" is more accurately described as being: its still visible but the grey fades into the surrounding white, losing the grey colouring and making it appear as a plain white background (so "losing" the thin striping).

Again, the lines are definitely present, and choosing a darker colouring for the lines, or changing the background colour of the row provides enough contrast for the grey lines to be shown.

2018-12-19 13:33 UTC, AllienWorks commented
Hold the phone here.. can you see the stripes in [this screenshot](https://user-images.githubusercontent.com/28861857/50149171-1d011800-02c3-11e9-8549-18aba7fc72a2.png)?
Answer to this will easily reveal the issue. It's not _only_ the stripes there; even the background of expired items is darker (same as generic app background, the light grey).

2018-12-19 14:22 UTC, EagleEye25 commented
@AllienWorks on the 4k screen i cant see any difference, its just white, but when i take it over to the 1080p screen i can see the stripes.

2018-12-20 15:08 UTC, zaSmilingIdiot approved these changes

2018-12-20 15:09 UTC, merged

2018-12-20 15:13 UTC, zaSmilingIdiot commented
Implements https://github.com/particl/particl-desktop/issues/1285