- Listing expiry time counter
particl/particl-desktop pull request #1333
Opened 2018-12-20 13:39 UTC by cis-shubham-t

- Added the listing expiry time in listing preview.
- Added the listing expiry count-down in listing preview.
- Added the listing expiry time in the checkout process.

2018-12-20 13:39 UTC, cis-shubham-t commented
Task: https://particl.atlassian.net/projects/PBD/issues/PBD-95

2018-12-20 13:42 UTC, cis-shubham-t commented
hey @AllienWorks 
I've added the time counter for the listing could you please have a look at the listing preview popup and make highlighted (maybe with red).

I'm not put the condition for the counter only visible if the listing expiry in the next 24 hours.  so you can see the counter time for the each listing.

2018-12-21 17:46 UTC, AllienWorks commented
I've styled this, both on listing preview & in cart. Also activated the condition for hiding of the "expires soon" messages (@cis-shubham-t please double-check if it's working correctly :)

![screenshot from 2018-12-21 17-45-04](https://user-images.githubusercontent.com/1965795/50355979-b133df00-0550-11e9-836d-e1f0cc567462.png)

2018-12-26 15:55 UTC, zaSmilingIdiot requested changes

2018-12-26 15:55 UTC, zaSmilingIdiot commented on src/app/market/listings/preview-listing/preview-listing.component.ts
> +    console.log('this.data', this.data);
Please remove this line, or change it to a debug log statement.

2018-12-26 15:55 UTC, zaSmilingIdiot commented on src/app/market/listings/preview-listing/preview-listing.component.html
> +            {{ data?.listing?.expireIn }} left
Maybe take the word 'left' out here... if the time is counting down then the meaning is somewhat clear.

2018-12-26 15:55 UTC, zaSmilingIdiot commented on src/app/core/market/api/template/template.model.ts
> +  get isAboutToExpire(): any {
The body of this function can be collapsed/shortened into a single line:
`return this.object.expiredAt > +new Date() && ((this.object.expiredAt - +new Date()) <= 86400000);`

2018-12-26 15:55 UTC, zaSmilingIdiot commented on src/app/core/market/api/template/template.model.ts
> +  get isAboutToExpire(): any {
Also, the return type is boolean, not any

2018-12-26 15:55 UTC, zaSmilingIdiot commented on src/app/core/market/api/template/template.model.ts
> +  get expireIn(): any {
please change the return type

2018-12-28 16:30 UTC, zaSmilingIdiot approved these changes

2018-12-28 16:31 UTC, merged