fixed high res issue on sell page
particl/particl-desktop pull request #1393
Opened 2019-01-31 12:17 UTC by EagleEye25

2019-02-01 02:41 UTC, kewde commented
I think this code will clear the page on every resize and load the first page.

2019-02-01 02:52 UTC, kewde requested changes

2019-02-01 02:52 UTC, kewde commented on src/app/market/sell/sell.component.ts
> +  screenWidth: number;
rm

2019-02-01 02:52 UTC, kewde commented on src/app/market/sell/sell.component.ts
> +    this.screenHeight > 1330 ? max = 20 : max = this.pagination.maxPerPage;
rm, just set `this.pagination.maxPerPage` equal to 20

2019-02-01 02:52 UTC, kewde commented on src/app/market/sell/sell.component.ts
> +    this.screenWidth = window.innerWidth;
rm

2019-02-01 02:52 UTC, kewde commented on src/app/market/sell/sell.component.ts
> +    if (this.screenHeight > 1330) {
Maybe something like this?
```
this.pagination.maxPerPage = window.innerWidth > 1330 ? 20 : 10;

if (screenIsNowLarger) {
   // load next page
   this.loadNextPage();
} 
```

2019-02-01 02:53 UTC, kewde commented on src/app/market/sell/sell.component.ts
> +      this.loadPage(0, true);
This will reset everything, so if you do it midway a search, you lose stuff

2019-02-06 13:43 UTC, zaSmilingIdiot approved these changes

2019-02-06 13:47 UTC, merged